# Generated by Django 3.1.4 on 2020-12-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_allgrocery_name_english'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllGrocery',
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
