# Generated by Django 3.1.4 on 2020-12-17 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_grocery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='coordinate',
        ),
    ]
