# Generated by Django 3.1.4 on 2020-12-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_remove_grocery_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='coordinate',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
